-- MySQL Script generated by MySQL Workbench
-- Thu Oct 20 14:54:59 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema la_vie_pess
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema la_vie_pess
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `la_vie_pess` DEFAULT CHARACTER SET utf8 ;
USE `la_vie_pess` ;

-- -----------------------------------------------------
-- Table `la_vie_pess`.`pacientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `la_vie_pess`.`pacientes` ;

CREATE TABLE IF NOT EXISTS `la_vie_pess`.`pacientes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `idade` DATE NOT NULL,
  `createdAt` TIMESTAMP NULL,
  `updatedAt` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `la_vie_pess`.`psicologos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `la_vie_pess`.`psicologos` ;

CREATE TABLE IF NOT EXISTS `la_vie_pess`.`psicologos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(60) NOT NULL,
  `apresentacao` TEXT NOT NULL,
  `createdAt` TIMESTAMP NULL,
  `updatedAt` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `la_vie_pess`.`atendimentos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `la_vie_pess`.`atendimentos` ;

CREATE TABLE IF NOT EXISTS `la_vie_pess`.`atendimentos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data_atendimento` TIMESTAMP NOT NULL,
  `observacao` TEXT NOT NULL,
  `createdAt` TIMESTAMP NULL,
  `updatedAt` TIMESTAMP NULL,
  `pacientes_id` INT NOT NULL,
  `psicologos_id` INT NOT NULL,
  INDEX `fk_atendimentos_pacientes_idx` (`pacientes_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  INDEX `fk_atendimentos_psicologos1_idx` (`psicologos_id` ASC) VISIBLE,
  CONSTRAINT `fk_atendimentos_pacientes`
    FOREIGN KEY (`pacientes_id`)
    REFERENCES `la_vie_pess`.`pacientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_atendimentos_psicologos1`
    FOREIGN KEY (`psicologos_id`)
    REFERENCES `la_vie_pess`.`psicologos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
